In [1]:
from sklearn.model_selection import train_test_split
Y = df["default"]
X = df.drop(columns = ["default"])

# Split our data
train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                          test_size=0.2)





NameError: name 'df' is not defined

In [2]:
import pandas as pd
import numpy as np

#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [3]:
from sklearn.model_selection import train_test_split
Y = df["default"]
X = df.drop(columns = ["default"])

# Split our data
train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                          test_size=0.2)





In [4]:
from sklearn.model_selection import train_test_split
Y = df["default"]
X = df.drop(columns = ["default"])

# Split our data
train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
print(train)
print(train_labels)                                                        test_size=0.2)





SyntaxError: invalid syntax (<ipython-input-4-3086ee39191b>, line 9)

In [5]:
from sklearn.model_selection import train_test_split
Y = df["default"]
X = df.drop(columns = ["default"])

# Split our data
train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                          test_size=0.2)
print(train)
print(train_labels)   





     age  ed  employ  address  income  debtinc   creddebt    othdebt
64    26   2       5        7      28      7.8   1.024296   1.159704
428   23   1       2        1      25      4.5   0.123750   1.001250
315   36   1       4       15      17     17.3   0.520557   2.420443
465   28   1       4        1      16     23.8   1.085280   2.722720
59    50   3      10       20      80     12.2   2.479040   7.280960
..   ...  ..     ...      ...     ...      ...        ...        ...
106   53   1       9       18      50     11.2   2.016000   3.584000
66    28   2       2        3      23      6.4   0.186944   1.285056
373   33   1      14        8      72     41.3  15.016680  14.719320
144   41   1      16       17      68      5.4   0.447984   3.224016
33    25   1       8        4      27     14.4   1.018656   2.869344

[560 rows x 8 columns]
64     0.0
428    1.0
315    0.0
465    0.0
59     0.0
      ... 
106    1.0
66     1.0
373    1.0
144    0.0
33     0.0
Name: default, Length: 560,

In [6]:

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
# Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)
print(preds)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [7]:
print(accuracy_score(test_labels, preds))





NameError: name 'accuracy_score' is not defined

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [9]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [10]:
gnb = GaussianNB()
# Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)




In [11]:
print(accuracy_score(test_labels, preds))







0.7571428571428571


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [2]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [3]:
gnb = GaussianNB()
# Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)




In [4]:
print(accuracy_score(test_labels, preds))







0.7285714285714285


In [5]:
print(accuracy_score(test_labels, preds))







0.7285714285714285


In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [7]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [8]:
breakpoint()
print(accuracy_score(test_labels, preds))



0.6642857142857143


In [9]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)



In [10]:
print(accuracy_score(test_labels, preds_gnb))
print(accuracy_score(test_labels, preds_lr))






0.7571428571428571
0.8071428571428572


In [11]:
print("accuracy")
print(accuracy_score(test_labels, preds_gnb))
print(accuracy_score(test_labels, preds_lr))

print("f1")
print(f1_score(test_labels, preds_gnb))
print(f1_score(test_labels, preds_lr))




accuracy
0.7571428571428571
0.8071428571428572
f1


NameError: name 'f1_score' is not defined

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [13]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [14]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)



In [15]:
print("accuracy")
print(accuracy_score(test_labels, preds_gnb))
print(accuracy_score(test_labels, preds_lr))

print("f1") #2* (precision*recall)/(precision+recall)
print(f1_score(test_labels, preds_gnb))
print(f1_score(test_labels, preds_lr))




accuracy
0.7642857142857142
0.7928571428571428
f1
0.3773584905660377
0.5797101449275363


In [16]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)
preds_proba_lr = lr.predict_proba(test)

print(preds_lr[0:20])
print(preds_proba_lr[0:20])

[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[[0.90496807 0.09503193]
 [0.32319215 0.67680785]
 [0.81901315 0.18098685]
 [0.7310212  0.2689788 ]
 [0.79372196 0.20627804]
 [0.76595185 0.23404815]
 [0.4030185  0.5969815 ]
 [0.99490441 0.00509559]
 [0.75910232 0.24089768]
 [0.66120734 0.33879266]
 [0.99801893 0.00198107]
 [0.82259579 0.17740421]
 [0.84174133 0.15825867]
 [0.68810678 0.31189322]
 [0.69161051 0.30838949]
 [0.94207762 0.05792238]
 [0.92633924 0.07366076]
 [0.43847362 0.56152638]
 [0.84313453 0.15686547]
 [0.91401386 0.08598614]]


In [17]:
print("accuracy")
print(accuracy_score(test_labels, preds_gnb))
print(accuracy_score(test_labels, preds_lr))

print("precision")
print(precision(test_labels, preds_gnb))
print(recall(test_labels, preds_lr))

print("recall")
print(precision(test_labels, preds_gnb))
print(recall(test_labels, preds_lr))



accuracy
0.7642857142857142
0.7928571428571428
precision


NameError: name 'precision' is not defined

In [18]:
print("accuracy")
print(accuracy_score(test_labels, preds_gnb))
print(accuracy_score(test_labels, preds_lr))

print("precision")
print(precision(test_labels, preds_gnb))
print(recall(test_labels, preds_lr))

print("recall")
print(precision(test_labels, preds_gnb))
print(recall(test_labels, preds_lr))



accuracy
0.7642857142857142
0.7928571428571428
precision


NameError: name 'precision' is not defined

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [20]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [21]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [22]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)
preds_proba_lr = lr.predict_proba(test)

print(preds_lr[0:20])
print(preds_proba_lr[0:20])

[1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
[[0.33147633 0.66852367]
 [0.95069109 0.04930891]
 [0.49126501 0.50873499]
 [0.78140191 0.21859809]
 [0.73135072 0.26864928]
 [0.31153863 0.68846137]
 [0.88512235 0.11487765]
 [0.87602837 0.12397163]
 [0.84263544 0.15736456]
 [0.91935146 0.08064854]
 [0.97712297 0.02287703]
 [0.99767468 0.00232532]
 [0.4425939  0.5574061 ]
 [0.93764899 0.06235101]
 [0.17972416 0.82027584]
 [0.69686351 0.30313649]
 [0.99648625 0.00351375]
 [0.98048579 0.01951421]
 [0.61856512 0.38143488]
 [0.56424604 0.43575396]]


In [23]:
print("accuracy")
print(accuracy_score(test_labels, preds_gnb))
print(accuracy_score(test_labels, preds_lr))

print("precision")
print(precision_score(test_labels, preds_gnb))
print(recall_score(test_labels, preds_lr))

print("recall")
print(precision(test_labels, preds_gnb))
print(recall(test_labels, preds_lr))



accuracy
0.7785714285714286
0.8357142857142857
precision
0.4
0.5517241379310345
recall


NameError: name 'precision' is not defined

In [24]:
print("accuracy")
print("gnb" + accuracy_score(test_labels, preds_gnb))
print("lr " +accuracy_score(test_labels, preds_lr))

print("precision")
print(precision_score(test_labels, preds_gnb))
print(recall_score(test_labels, preds_lr))

print("recall")
print(precision(test_labels, preds_gnb))
print(recall(test_labels, preds_lr))



accuracy


TypeError: can only concatenate str (not "numpy.float64") to str

In [25]:
print("Logistic Regression")
print("accuracy")
print(accuracy_score(test_labels, preds_lr))
print("precision")
print(precision_score(test_labels, preds_lr))
print("recall")
print(recall_score(test_labels, preds_lr))





Logistic Regression
accuracy
0.8357142857142857
precision
0.6153846153846154
recall
0.5517241379310345


In [26]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)
preds_proba_lr = lr.predict_proba(test)

print(preds_lr[0:20])
print(preds_proba_lr[0:20])


[1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
[[0.33147633 0.66852367]
 [0.95069109 0.04930891]
 [0.49126501 0.50873499]
 [0.78140191 0.21859809]
 [0.73135072 0.26864928]
 [0.31153863 0.68846137]
 [0.88512235 0.11487765]
 [0.87602837 0.12397163]
 [0.84263544 0.15736456]
 [0.91935146 0.08064854]
 [0.97712297 0.02287703]
 [0.99767468 0.00232532]
 [0.4425939  0.5574061 ]
 [0.93764899 0.06235101]
 [0.17972416 0.82027584]
 [0.69686351 0.30313649]
 [0.99648625 0.00351375]
 [0.98048579 0.01951421]
 [0.61856512 0.38143488]
 [0.56424604 0.43575396]]


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [2]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [3]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)
preds_proba_lr = lr.predict_proba(test)

print(preds_lr[0:20])
print(preds_proba_lr[0:20])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
[[0.60042248 0.39957752]
 [0.50830926 0.49169074]
 [0.97150494 0.02849506]
 [0.98824994 0.01175006]
 [0.98098311 0.01901689]
 [0.82749847 0.17250153]
 [0.65068456 0.34931544]
 [0.99306094 0.00693906]
 [0.67766153 0.32233847]
 [0.67983728 0.32016272]
 [0.6745874  0.3254126 ]
 [0.84629594 0.15370406]
 [0.5177087  0.4822913 ]
 [0.37318628 0.62681372]
 [0.16458208 0.83541792]
 [0.75111141 0.24888859]
 [0.55121899 0.44878101]
 [0.81826393 0.18173607]
 [0.99628686 0.00371314]
 [0.58669362 0.41330638]]


In [4]:
print("Logistic Regression")
print("accuracy")
print(accuracy_score(test_labels, preds_lr))
print("precision")
print(precision_score(test_labels, preds_lr))
print("recall")
print(recall_score(test_labels, preds_lr))





Logistic Regression
accuracy
0.7857142857142857
precision
0.92
recall
0.45098039215686275


In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [6]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [7]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)
preds_proba_lr = lr.predict_proba(test)

print(preds_lr[0:20])
print(preds_proba_lr[0:20])


[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
[[8.43079815e-01 1.56920185e-01]
 [1.80208930e-01 8.19791070e-01]
 [7.60420760e-01 2.39579240e-01]
 [8.89779240e-01 1.10220760e-01]
 [9.90680657e-01 9.31934341e-03]
 [7.44668523e-01 2.55331477e-01]
 [7.77030872e-01 2.22969128e-01]
 [9.77638994e-01 2.23610062e-02]
 [7.89262538e-01 2.10737462e-01]
 [8.32380227e-01 1.67619773e-01]
 [5.17385286e-01 4.82614714e-01]
 [9.99707290e-01 2.92709959e-04]
 [6.60552682e-01 3.39447318e-01]
 [7.64239879e-01 2.35760121e-01]
 [9.02841362e-01 9.71586376e-02]
 [5.20106863e-01 4.79893137e-01]
 [4.44526733e-01 5.55473267e-01]
 [8.62584343e-01 1.37415657e-01]
 [8.95254959e-01 1.04745041e-01]
 [3.23905862e-01 6.76094138e-01]]


In [8]:
print("Logistic Regression")
print("accuracy")
print(accuracy_score(test_labels, preds_lr))
print("precision")
print(precision_score(test_labels, preds_lr))
print("recall")
print(recall_score(test_labels, preds_lr))





Logistic Regression
accuracy
0.8142857142857143
precision
0.7083333333333334
recall
0.4722222222222222


In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score


#data loading
df = pd.read_csv("data.csv")
print(df.head)

#shape - controllo dimensionalità
print(df.shape)
#info - controllo tipi
print(df.info())
#drop nan - rimozione righe con valori nulli
df.dropna(inplace = True)

#descrizione 
print(df.describe())
df['default'].sum()




<bound method NDFrame.head of      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]>
(850, 9)
<class 'pand

183.0

In [10]:
Y = df["default"]
X = df.drop(columns = ["default"])

train, test, train_labels, test_labels = train_test_split(X,
                                                          Y,
                                                        test_size=0.2)
 

In [11]:
gnb = GaussianNB()
lr = LogisticRegression()
# Train our classifier
model_gnb = gnb.fit(train, train_labels)
model_lr = lr.fit(train, train_labels)
preds_gnb = gnb.predict(test)
preds_lr = lr.predict(test)
preds_proba_lr = lr.predict_proba(test)

print(preds_lr[0:20])
print(preds_proba_lr[0:20])


[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.88961769 0.11038231]
 [0.6790422  0.3209578 ]
 [0.74925136 0.25074864]
 [0.8948962  0.1051038 ]
 [0.99756399 0.00243601]
 [0.72360764 0.27639236]
 [0.34310078 0.65689922]
 [0.98393167 0.01606833]
 [0.78340821 0.21659179]
 [0.99640952 0.00359048]
 [0.98006283 0.01993717]
 [0.35119833 0.64880167]
 [0.76975099 0.23024901]
 [0.99005118 0.00994882]
 [0.99882009 0.00117991]
 [0.98676964 0.01323036]
 [0.99365573 0.00634427]
 [0.97088403 0.02911597]
 [0.65621763 0.34378237]
 [0.81788853 0.18211147]]


In [12]:
print("Logistic Regression")
print("accuracy")
print(accuracy_score(test_labels, preds_lr))
print("precision")
print(precision_score(test_labels, preds_lr))
print("recall")
print(recall_score(test_labels, preds_lr))





Logistic Regression
accuracy
0.85
precision
0.8333333333333334
recall
0.5405405405405406
